"""Add owner_id and indexes

Revision ID: c7a59cf9f3dd
Revises: 
Create Date: 2026-01-17 08:09:03.227132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7a59cf9f3dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_campaigns_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_campaigns_owner_created', ['owner_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_owner_id'))
        batch_op.drop_index('ix_campaigns_owner_created')
        batch_op.drop_index(batch_op.f('ix_campaigns_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
